# Generated by Django 5.2.13 on 2026-04-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reporting_id', models.CharField(blank=True, max_length=20, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('China', 'China')], max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('payment_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=20)),
                ('payment_term', models.CharField(choices=[('15 Days', '15 Days'), ('30 Days', '30 Days'), ('45 Days', '45 Days')], max_length=20)),
                ('billing_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], max_length=10)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_no', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_country', models.CharField(max_length=100)),
                ('contact_zipcode', models.CharField(max_length=20)),
                ('contact_address_1', models.CharField(max_length=300)),
                ('contact_address_2', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_signature', models.FileField(upload_to='signatures/')),
                ('company_address_line1', models.CharField(max_length=300)),
                ('company_address_line2', models.CharField(blank=True, max_length=300, null=True)),
                ('company_country', models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('UK', 'UK'), ('China', 'China')], max_length=50)),
                ('company_zipcode', models.CharField(max_length=10)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('user_password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
