# Generated by Django 5.2.13 on 2026-05-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbilling',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='app.client'),
        ),
        migrations.AlterField(
            model_name='clientclassification',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='app.client'),
        ),
        migrations.AlterField(
            model_name='clientownership',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='app.client'),
        ),
    ]
