# Generated by Django 5.2.13 on 2026-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_clientbilling_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
