# Generated by Django 5.2.13 on 2026-05-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_companycontact_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='digital_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
