# Generated by Django 5.2.13 on 2026-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_companycontact_digital_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='day_parting',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='pacing',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='total_budget',
        ),
    ]
