# Generated by Django 5.2.13 on 2026-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_campaign_budget_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
    ]
