# Generated by Django 5.2.13 on 2026-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_campaign_end_date_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='kpi_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
