# Generated by Django 5.2.13 on 2026-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_lineitem_kpi_notes_lineitem_unit_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='ctr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='vcr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='viewability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
