# Generated by Django 5.2.13 on 2026-05-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_lineitem_ctr_alter_lineitem_vcr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('client', 'Client'), ('creative', 'Creative')], max_length=20),
        ),
    ]
