# Generated by Django 5.2.13 on 2026-05-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_lineitem_end_date_alter_lineitem_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItemCreative',
        ),
    ]
