# Generated by Django 5.2.13 on 2026-05-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_lineitemcreative'),
    ]

    operations = [
        migrations.AddField(
            model_name='creative',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='creative',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='app.lineitem'),
        ),
    ]
