# Generated by Django 5.2.13 on 2026-05-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_creative_file_type_alter_creative_line_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creative',
            name='line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives_detail', to='app.lineitem'),
        ),
    ]
